<<<<<<< HEAD
-- CUMULATIVE ANALYSIS

-- CALCULATE THE TOTAL SALES PER MONTH AND THE RUNNING TOTAL OF SALES OVER TIME
-- FIRST WAY

-- BY MONTH
SELECT
ORDER_DATE,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES
FROM
(
SELECT
DATETRUNC(MONTH,order_date) AS ORDER_DATE,
SUM(sales_amount) AS TOTAL_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH,order_date)
) T


-- BY YEAR
SELECT
ORDER_DATE,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES
FROM
(
SELECT
DATETRUNC(YEAR,order_date) AS ORDER_DATE,
SUM(sales_amount) AS TOTAL_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(YEAR,order_date)
) T

-- TO FIND AVERAGE PRICE
SELECT
ORDER_DATE,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES,
AVG(AVG_PRICE) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS MOVING_AVERAGE_PRICE
FROM
(
SELECT
DATETRUNC(MONTH,order_date) AS ORDER_DATE,
SUM(sales_amount) AS TOTAL_SALES,
AVG(price) AS AVG_PRICE
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH,order_date)
) T

-- SECOND WAY
SELECT
ORDER_DATE_YEAR,
ORDER_DATE_MONTH,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE_YEAR ORDER BY ORDER_DATE_MONTH) AS RUNNING_TOTAL_SALES
FROM
(
SELECT
YEAR(order_date) AS ORDER_DATE_YEAR,
MONTH(order_date) AS ORDER_DATE_MONTH,
SUM(sales_amount) AS TOTAL_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date),MONTH(order_date)
) T
=======
-- CUMULATIVE ANALYSIS

-- CALCULATE THE TOTAL SALES PER MONTH AND THE RUNNING TOTAL OF SALES OVER TIME
-- FIRST WAY

-- BY MONTH
SELECT
ORDER_DATE,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES
FROM
(
SELECT
DATETRUNC(MONTH,order_date) AS ORDER_DATE,
SUM(sales_amount) AS TOTAL_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH,order_date)
) T


-- BY YEAR
SELECT
ORDER_DATE,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES
FROM
(
SELECT
DATETRUNC(YEAR,order_date) AS ORDER_DATE,
SUM(sales_amount) AS TOTAL_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(YEAR,order_date)
) T

-- TO FIND AVERAGE PRICE
SELECT
ORDER_DATE,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS RUNNING_TOTAL_SALES,
AVG(AVG_PRICE) OVER (PARTITION BY ORDER_DATE ORDER BY ORDER_DATE) AS MOVING_AVERAGE_PRICE
FROM
(
SELECT
DATETRUNC(MONTH,order_date) AS ORDER_DATE,
SUM(sales_amount) AS TOTAL_SALES,
AVG(price) AS AVG_PRICE
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(MONTH,order_date)
) T

-- SECOND WAY
SELECT
ORDER_DATE_YEAR,
ORDER_DATE_MONTH,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER (PARTITION BY ORDER_DATE_YEAR ORDER BY ORDER_DATE_MONTH) AS RUNNING_TOTAL_SALES
FROM
(
SELECT
YEAR(order_date) AS ORDER_DATE_YEAR,
MONTH(order_date) AS ORDER_DATE_MONTH,
SUM(sales_amount) AS TOTAL_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales]
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date),MONTH(order_date)
) T
>>>>>>> 5ba72aaa6e573711f502774dbe9f98f0ee4a32dc
