-- DATA SEGMENTATION

-- SEGMENT PRODUCTS INTO COST RANGES AND COUNT HOW MANY PRODUCTS FALL INTO EACH SEGMENT

WITH PRODUCT_SEGMENTS AS
(
SELECT 
product_key,
product_name,
cost,
CASE WHEN cost <100 THEN 'BELOW 100'
     WHEN cost BETWEEN 100 AND 500 THEN '100-500'
     WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
     ELSE 'ABOVE 1000'
END AS COST_RANGE  
FROM DataWarehouseAnalytics.dbo.[gold.products]
)
SELECT
COST_RANGE,
COUNT(product_key) AS TOTAL_PRODUCTS
FROM PRODUCT_SEGMENTS
GROUP BY COST_RANGE
ORDER BY TOTAL_PRODUCTS DESC


/*GROUP CUSTOMERS INTO THREE SEGMENTS BASED ON THEIR SPENDING BEHAVIOUR:
   -- VIP: CUSTOMERS WITH AT LEAST 12 MONTHS OF HISTORY AND SPENDING MORE THAN $5,000
   -- REGULAR: CUSTOMERS WITH AT LEAST 12 MONTHS OF HISTORY BUT SPENDING $5,000 OR LESS.
   -- NEW: CUSTOMERS WITH A LIFESPAN LESS THAN 12 MONTHS.
AND FIND THE TOTAL NUMBER OF CUSTOMER BY EACH GROUP*/
WITH CUSTOMER_SPENIDNG AS
(
SELECT 
C.customer_key,
SUM(S.sales_amount) AS TOTAL_SPENDING,
MIN(order_date) AS FIRST_ORDER,
MAX(order_date) AS LAST_ORDER,
DATEDIFF(MONTH, MIN(ORDER_DATE),MAX(ORDER_DATE)) AS LIFESPAN
FROM DataWarehouseAnalytics.dbo.[gold.sales] S
LEFT JOIN DataWarehouseAnalytics.dbo.[gold.customers] C
ON S.customer_key=C.customer_key
GROUP BY C.customer_key
)
SELECT
customer_key
,TOTAL_SPENDING
,LIFESPAN
,CASE WHEN LIFESPAN >=12 AND TOTAL_SPENDING > 5000 THEN 'VIP'
     WHEN LIFESPAN >=12 AND TOTAL_SPENDING <= 5000 THEN 'REGULAR'
     ELSE 'NEW'
END AS CUSTOMER_SEGMENT
FROM CUSTOMER_SPENIDNG

-- FIND THE TOTAL NUMBER OF CUSTOMER BY EACH GROUP

WITH CUSTOMER_SPENIDNG AS
(
SELECT 
C.customer_key,
SUM(S.sales_amount) AS TOTAL_SPENDING,
MIN(order_date) AS FIRST_ORDER,
MAX(order_date) AS LAST_ORDER,
DATEDIFF(MONTH, MIN(ORDER_DATE),MAX(ORDER_DATE)) AS LIFESPAN
FROM DataWarehouseAnalytics.dbo.[gold.sales] S
LEFT JOIN DataWarehouseAnalytics.dbo.[gold.customers] C
ON S.customer_key=C.customer_key
GROUP BY C.customer_key
)
SELECT
CUSTOMER_SEGMENT,
COUNT(CUSTOMER_KEY) AS TOTAL_CUSTOMERS
FROM
(
SELECT
CUSTOMER_KEY,
CASE WHEN LIFESPAN >=12 AND TOTAL_SPENDING > 5000 THEN 'VIP'
     WHEN LIFESPAN >=12 AND TOTAL_SPENDING <= 5000 THEN 'REGULAR'
     ELSE 'NEW'
END AS CUSTOMER_SEGMENT
FROM CUSTOMER_SPENIDNG) T
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_CUSTOMERS DESC