<<<<<<< HEAD
-- Performance Analysis

-- Analyze the yearly performance of products by comparing each product's sales to both its average sales performance and the previous year's sales.
WITH YEARLY_PRODUCT_SALES AS (
SELECT 
YEAR(S.order_date) AS ORDER_YEAR,
P.product_name,
SUM(S.sales_amount) AS CURRENT_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales] S
LEFT JOIN DataWarehouseAnalytics.dbo.[gold.products] P
ON S.product_key = P.product_key
WHERE S.order_date IS NOT NULL
GROUP BY YEAR(S.order_date),P.product_name
) 
SELECT
ORDER_YEAR,
product_name,
CURRENT_SALES,
-- YEAR-OVER-YEAR ANALYSIS
LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS PREVIOUS_SALES,
CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS DIFFERENCES_SALES,
AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS AVG_SALES,
CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS DIFF_AVG,
CASE WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) > 0 THEN 'ABOVE AVERAGE'
     WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) < 0 THEN 'BELOW AVERAGE'
     ELSE 'AVERAGE'
     END AS AVG_CHANGE,
CASE WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) > 0 THEN 'INCREASE'
     WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) < 0 THEN 'DECREASE'
     ELSE 'MAINTAIN'
     END AS SALES_CHANGE
FROM YEARLY_PRODUCT_SALES
=======
-- Performance Analysis

-- Analyze the yearly performance of products by comparing each product's sales to both its average sales performance and the previous year's sales.
WITH YEARLY_PRODUCT_SALES AS (
SELECT 
YEAR(S.order_date) AS ORDER_YEAR,
P.product_name,
SUM(S.sales_amount) AS CURRENT_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales] S
LEFT JOIN DataWarehouseAnalytics.dbo.[gold.products] P
ON S.product_key = P.product_key
WHERE S.order_date IS NOT NULL
GROUP BY YEAR(S.order_date),P.product_name
) 
SELECT
ORDER_YEAR,
product_name,
CURRENT_SALES,
-- YEAR-OVER-YEAR ANALYSIS
LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS PREVIOUS_SALES,
CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) AS DIFFERENCES_SALES,
AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS AVG_SALES,
CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) AS DIFF_AVG,
CASE WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) > 0 THEN 'ABOVE AVERAGE'
     WHEN CURRENT_SALES - AVG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME) < 0 THEN 'BELOW AVERAGE'
     ELSE 'AVERAGE'
     END AS AVG_CHANGE,
CASE WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) > 0 THEN 'INCREASE'
     WHEN CURRENT_SALES - LAG(CURRENT_SALES) OVER (PARTITION BY PRODUCT_NAME ORDER BY ORDER_YEAR) < 0 THEN 'DECREASE'
     ELSE 'MAINTAIN'
     END AS SALES_CHANGE
FROM YEARLY_PRODUCT_SALES
>>>>>>> 5ba72aaa6e573711f502774dbe9f98f0ee4a32dc
ORDER BY product_name,ORDER_YEAR