-- PROPORTIONAL ANALYSIS
-- PART TO WHOLE
-- WHICH CATEGORIES CONTRIBUTE THE MOST TO OVERALL SALES

WITH CATEGORY_SALES AS 
(
SELECT 
category,
SUM(sales_amount) AS TOTAL_SALES
FROM DataWarehouseAnalytics.dbo.[gold.sales] S
LEFT JOIN DataWarehouseAnalytics.dbo.[gold.products] P
ON S.product_key=P.product_key
GROUP BY category
)
SELECT
CATEGORY,
TOTAL_SALES,
SUM(TOTAL_SALES) OVER () AS OVERALL_SALES,
CONCAT(ROUND((CAST(TOTAL_SALES AS float)/SUM(TOTAL_SALES) OVER ())*100,2),'%') AS PERCENTAGE_OF_TOTAL
FROM CATEGORY_SALES
ORDER BY TOTAL_SALES DESC